###############################################################################
# Copyright (c) 2026, Advanced Micro Devices, Inc. All rights reserved.
#
# See LICENSE for license information.
###############################################################################

"""Opt-in workaround: run bf16/fp16 ``aten.mm`` calls in the layout of a Linear layer's forward GEMM.

On gfx1250 (MI455X), the shipped hipBLASLt tuning covers plain bf16 GEMMs (no bias or other
epilogue) only in the layout of a Linear layer's forward GEMM ``x @ W.t()``: TN in BLAS terms,
``Cijk_Alik_Bljk`` in hipBLASLt kernel names. The two backward GEMMs use other layouts:

* dgrad ``dX = dY @ W``: A and B both row-major (NN, ``Cijk_Ailk_Bljk``);
* wgrad ``dW = dY.t() @ X``: A a transposed view, B row-major (NT, ``Cijk_Ailk_Bjlk``).

For these layouts hipBLASLt falls back to kernels tuned for other problems. At Llama-3.1-8B
training shapes it picked a small tile (``MT32x16x32``), and timed with plain bf16 ``torch.mm``
on MI455X these GEMMs ran more than an order of magnitude slower than the forward layout at the
same shapes.

This module provides a ``TorchDispatchMode`` that intercepts ``aten.mm`` and hands hipBLASLt
the same logical matrices in the forward's physical layout, with ``Bn`` denoting B copied
into N-major order (``B.t().contiguous().t()``):

* dgrad -- A and B contiguous, B at least ``min_bytes``: ``mm(A, Bn)``;
* wgrad -- A a transposed view of a contiguous tensor, B contiguous, A at least
  ``min_bytes``: ``mm(A.contiguous(), Bn)``.

The rules match storage layouts, not autograd phases: any ``mm`` call in one of these layouts
is rewritten, and every other call, including the Linear forward GEMM, is left alone. fp16
calls are rewritten like bf16 ones, although the shipped tuning covers plain fp16 GEMMs in no
layout; the effect on fp16 has not been measured.

The copies use a tiled Triton transpose (:mod:`primus_turbo.triton.utils.transpose_kernel`), or
torch copies when Triton is unavailable. They add memory traffic, small next to the arithmetic
of a large GEMM; ``min_bytes`` leaves small GEMMs alone. Results are not bitwise identical to
the original call: a different kernel sums the products in a different order, at the same
accumulation precision.

Memory: an operand copy larger than ``chunk_bytes`` is avoided by splitting the GEMM into
blocks of output columns and, for wgrad, output rows (at least 256 wide) -- never along K, so
every output element is still reduced by one GEMM call. A column-split GEMM computes each block
into a temporary before copying it into the output. Temporaries come from scratch buffers kept
per (device, stream, dtype), 2.25 x ``chunk_bytes`` in all, allocated on first use and reused
until the workaround is disabled, so after warm-up a rewritten call allocates only its output,
like the original ``mm``. A temporary that does not fit its buffer, or that is needed while the
stream is being captured into a CUDA graph, is allocated fresh.

Scope:

* Like any dispatch mode, the workaround is thread-local. It covers ``aten.mm`` calls issued on
  the thread that enabled it, including the backward passes that thread runs (autograd carries
  dispatch modes over to its worker threads).
* Only plain CUDA (HIP) tensors are rewritten. Tensor subclasses with their own
  ``__torch_dispatch__`` (DTensor, FakeTensor, ...) dispatch as usual.
* While enabled, every aten op on the thread, not only ``mm``, makes a Python round trip
  through the mode: extra host time per op.
* ``torch.compile`` keeps compiling; GEMMs generated by Inductor are not rewritten.

Remove the workaround once hipBLASLt ships tuned kernels for these layouts.

Example::

    from primus_turbo.pytorch.core.mm_layout_workaround import enable_mm_layout_workaround

    enable_mm_layout_workaround()  # once, on the training thread, before the first step
"""

import contextlib
import functools
import operator
import threading
from typing import Callable, Dict, Iterator, NamedTuple, Optional

import torch
from torch.utils._python_dispatch import (
    TorchDispatchMode,
    _get_current_dispatch_mode,
    _get_current_dispatch_mode_stack,
)

from primus_turbo.common.logger import logger

__all__ = [
    "disable_mm_layout_workaround",
    "enable_mm_layout_workaround",
    "mm_layout_workaround",
    "mm_layout_workaround_enabled",
]

_DEFAULT_MIN_BYTES = 4 << 20
_DEFAULT_CHUNK_BYTES = 256 << 20

_MM = torch.ops.aten.mm.default
_MM_OUT = torch.ops.aten.mm.out
_DTYPES = (torch.bfloat16, torch.float16)
# Device types whose mm calls are rewritten ("cuda" includes HIP). The unit tests add "cpu" to
# exercise the rewrite without a GPU.
_REWRITE_DEVICE_TYPES = ("cuda",)
# Row and column blocks of a split GEMM are multiples of this.
_BLOCK_ALIGN = 256


class _Config(NamedTuple):
    min_bytes: int
    chunk_bytes: int


def _make_config(min_bytes, chunk_bytes) -> _Config:
    min_bytes = operator.index(min_bytes)
    chunk_bytes = operator.index(chunk_bytes)
    if min_bytes < 0:
        raise ValueError(f"min_bytes must be >= 0, got {min_bytes}")
    if chunk_bytes <= 0:
        raise ValueError(f"chunk_bytes must be > 0, got {chunk_bytes}")
    return _Config(min_bytes, chunk_bytes)


def _nbytes(t: torch.Tensor) -> int:
    return t.numel() * t.element_size()


def _rewrite_kind(a: torch.Tensor, b: torch.Tensor, min_bytes: int) -> Optional[str]:
    """Which rewrite applies to ``mm(a, b)``: ``"dgrad"``, ``"wgrad"`` or None (leave it alone)."""
    if not (
        a.layout == torch.strided
        and b.layout == torch.strided
        and a.dim() == 2
        and b.dim() == 2
        and a.dtype == b.dtype
        and a.dtype in _DTYPES
        and a.device == b.device
        and a.device.type in _REWRITE_DEVICE_TYPES
        and a.numel() > 0
        and b.numel() > 0
        and b.is_contiguous()
    ):
        return None
    if a.is_contiguous():
        return "dgrad" if _nbytes(b) >= min_bytes else None
    if a.t().is_contiguous():
        return "wgrad" if _nbytes(a) >= min_bytes else None
    return None


@functools.lru_cache(maxsize=None)
def _triton_transpose_into() -> Optional[Callable[[torch.Tensor, torch.Tensor], torch.Tensor]]:
    """The Triton transpose, or None when Triton is unavailable (logged once)."""
    try:
        from primus_turbo.triton.utils.transpose_kernel import transpose_into
    except ImportError as exc:
        logger.warning(
            "mm layout workaround: Triton is unavailable (%s); operand transposes use torch copies.",
            exc,
            once=True,
        )
        return None
    return transpose_into


def _transpose_into(y: torch.Tensor, x: torch.Tensor) -> None:
    """``y`` (C, R), contiguous <- ``x.T`` for ``x`` (R, C) with any strides."""
    transpose_into = _triton_transpose_into() if y.is_cuda else None
    if transpose_into is not None:
        transpose_into(y, x)
    else:
        y.copy_(x.t())


def _buffer(
    pool: Optional[Dict[str, torch.Tensor]], like: torch.Tensor, which: str, numel: int, chunk_bytes: int
) -> torch.Tensor:
    """A 1-D temporary of ``numel`` elements: a prefix of scratch buffer ``which`` or a fresh tensor."""
    # "a" and "b" hold operand copies, bounded by chunk_bytes. "o" holds a block of output
    # columns, which only exists when B is too large to copy whole -- typically because K is
    # large, which keeps the block narrow; a quarter of the budget covers the common cases.
    cap = chunk_bytes // 4 if which == "o" else chunk_bytes
    element_size = like.element_size()
    if pool is None or numel * element_size > cap:
        return torch.empty(numel, device=like.device, dtype=like.dtype)
    buf = pool.get(which)
    if buf is None:
        buf = pool[which] = torch.empty(cap // element_size, device=like.device, dtype=like.dtype)
    return buf[:numel]


def _chunked_mm(
    a: torch.Tensor,
    b: torch.Tensor,
    copy_a: bool,
    chunk_bytes: int,
    pool: Optional[Dict[str, torch.Tensor]],
) -> torch.Tensor:
    """``mm(a, b)`` with B handed over N-major, and A row-major when ``copy_a``.

    Splits the output into column blocks (and, when A is copied, row blocks) so that operand
    copies stay within ``chunk_bytes`` (blocks are at least 256 wide); every output element
    keeps its full K reduction.
    """
    m, k = a.shape
    n = b.shape[1]
    element_size = a.element_size()
    block = max(_BLOCK_ALIGN, chunk_bytes // (k * element_size) // _BLOCK_ALIGN * _BLOCK_ALIGN)
    cols = n if k * n * element_size <= chunk_bytes else block
    rows = m if (not copy_a or m * k * element_size <= chunk_bytes) else block
    out = torch.empty((m, n), device=a.device, dtype=a.dtype)
    for c0 in range(0, n, cols):
        c1 = min(n, c0 + cols)
        b_nmajor = _buffer(pool, b, "b", k * (c1 - c0), chunk_bytes).view(c1 - c0, k)
        _transpose_into(b_nmajor, b[:, c0:c1])
        b_nmajor = b_nmajor.t()  # logical (k, c1 - c0), physically N-major
        for r0 in range(0, m, rows):
            r1 = min(m, r0 + rows)
            if copy_a:
                a_rows = _buffer(pool, a, "a", (r1 - r0) * k, chunk_bytes).view(r1 - r0, k)
                _transpose_into(a_rows, a[r0:r1].t())
            else:
                a_rows = a[r0:r1]
            if cols == n:
                _MM_OUT(a_rows, b_nmajor, out=out[r0:r1])
            else:
                out_block = _buffer(pool, a, "o", (r1 - r0) * (c1 - c0), chunk_bytes)
                out_block = out_block.view(r1 - r0, c1 - c0)
                _MM_OUT(a_rows, b_nmajor, out=out_block)
                out[r0:r1, c0:c1].copy_(out_block)
    return out


class _MMLayoutWorkaroundMode(TorchDispatchMode):
    # Pass higher-order operators (torch.cond, flex_attention, ...) through instead of
    # refusing them.
    supports_higher_order_operators = True

    @classmethod
    def ignore_compile_internals(cls) -> bool:
        # An active user dispatch mode otherwise makes torch.compile fall back to eager.
        return True

    def __init__(self, config: _Config):
        super().__init__()
        self.config = config
        # (device, stream, dtype) -> {"a" | "b" | "o": 1-D scratch tensor}
        self._scratch: Dict[tuple, Dict[str, torch.Tensor]] = {}
        # Held while a rewrite is enqueued, so that work from another thread on the same stream
        # cannot interleave with it and overwrite a scratch buffer the rewrite still reads.
        self._lock = threading.Lock()

    def configure(self, config: _Config) -> None:
        with self._lock:
            if config.chunk_bytes != self.config.chunk_bytes:
                self._scratch.clear()  # the buffers are sized by chunk_bytes
            self.config = config

    def release(self) -> None:
        with self._lock:
            self._scratch.clear()

    def __torch_dispatch__(self, func, types, args=(), kwargs=None):
        kwargs = kwargs or {}
        # With a mode active, C++ also hands the shallow-copy detach of a plain tensor (autograd
        # saving an op's own output, Tensor.data) to the mode, with that tensor's own type, e.g.
        # torch.Tensor or nn.Parameter, in `types`. Only a type that overrides
        # __torch_dispatch__ is a tensor subclass that can take the call.
        if any(t.__torch_dispatch__ is not torch._C._disabled_torch_dispatch_impl for t in types):
            # A tensor subclass with its own __torch_dispatch__ (DTensor, FakeTensor, ...) is
            # never rewritten itself. With no other mode below this one, NotImplemented hands
            # the call to the subclass while this mode stays active, so the plain-tensor GEMMs
            # the subclass issues are still covered. Otherwise the modes below (e.g. fake or
            # functional tracing) must see the call, so pass it down the stack.
            if _get_current_dispatch_mode() is None:
                return NotImplemented
            return func(*args, **kwargs)
        if func is _MM and not kwargs:
            a, b = args
            kind = _rewrite_kind(a, b, self.config.min_bytes)
            if kind is not None:
                return self._rewrite(a, b, copy_a=kind == "wgrad")
        return func(*args, **kwargs)

    def _rewrite(self, a: torch.Tensor, b: torch.Tensor, copy_a: bool) -> torch.Tensor:
        with self._lock:
            chunk_bytes = self.config.chunk_bytes
            if not a.is_cuda:
                pool = self._scratch.setdefault((a.device, None, a.dtype), {})
                return _chunked_mm(a, b, copy_a, chunk_bytes, pool)
            with torch.cuda.device(a.device):
                pool = None
                # A buffer kept across a CUDA graph capture would tie eager work and graph
                # replays to the same memory; captured rewrites use fresh temporaries.
                if not torch.cuda.is_current_stream_capturing():
                    stream = torch.cuda.current_stream().cuda_stream
                    pool = self._scratch.setdefault((a.device, stream, a.dtype), {})
                return _chunked_mm(a, b, copy_a, chunk_bytes, pool)


class _ThreadState(threading.local):
    def __init__(self):
        self.mode: Optional[_MMLayoutWorkaroundMode] = None


_state = _ThreadState()


def enable_mm_layout_workaround(
    min_bytes: int = _DEFAULT_MIN_BYTES, chunk_bytes: int = _DEFAULT_CHUNK_BYTES
) -> None:
    """Rewrite backward-layout bf16/fp16 ``aten.mm`` calls on the calling thread.

    Idempotent: when the workaround is already enabled on this thread, only its settings are
    updated. See the module docstring for what is rewritten and why.

    Args:
        min_bytes: Rewrite a dgrad call only when B, and a wgrad call only when A, holds at
            least this many bytes. For smaller GEMMs the copies can cost more than they save.
        chunk_bytes: Budget for each operand copy; GEMMs whose copies would exceed it are
            split along their output columns and rows. The scratch buffers take up to 2.25x
            this per (device, stream, dtype).
    """
    config = _make_config(min_bytes, chunk_bytes)
    _triton_transpose_into()  # resolve now, so that a missing Triton is reported at enable time
    mode = _state.mode
    if mode is not None:
        mode.configure(config)
        return
    mode = _MMLayoutWorkaroundMode(config)
    mode.__enter__()
    _state.mode = mode
    logger.info(
        "mm layout workaround enabled (min_bytes=%d, chunk_bytes=%d)", config.min_bytes, config.chunk_bytes
    )


def disable_mm_layout_workaround() -> None:
    """Undo :func:`enable_mm_layout_workaround` on the calling thread and free its scratch buffers.

    A no-op when the workaround is not enabled on this thread.

    Raises:
        RuntimeError: Another ``TorchDispatchMode`` entered on this thread after the
            workaround was enabled is still active; exit it first.
    """
    mode = _state.mode
    if mode is None:
        return
    if _get_current_dispatch_mode() is not mode:
        raise RuntimeError(
            "disable_mm_layout_workaround: a TorchDispatchMode entered after "
            "enable_mm_layout_workaround is still active on this thread; exit it first."
        )
    mode.__exit__(None, None, None)
    _state.mode = None
    mode.release()
    logger.info("mm layout workaround disabled")


def mm_layout_workaround_enabled() -> bool:
    """Whether ``aten.mm`` calls issued on the calling thread go through the workaround."""
    return any(isinstance(mode, _MMLayoutWorkaroundMode) for mode in _get_current_dispatch_mode_stack())


@contextlib.contextmanager
def mm_layout_workaround(
    min_bytes: int = _DEFAULT_MIN_BYTES, chunk_bytes: int = _DEFAULT_CHUNK_BYTES
) -> Iterator[None]:
    """Enable the workaround on the calling thread for the duration of a ``with`` block.

    Takes the arguments of :func:`enable_mm_layout_workaround`. On exit the previous state is
    restored: disabled again, or enabled with the previous settings.
    """
    previous = _state.mode.config if _state.mode is not None else None
    enable_mm_layout_workaround(min_bytes, chunk_bytes)
    try:
        yield
    finally:
        if previous is None:
            disable_mm_layout_workaround()
        else:
            enable_mm_layout_workaround(*previous)
